var currentLang = 'en';

var T = {
en: {
  /* NAV */
  'nav.home':'Home','nav.reg':'Patient Registration',
  /* BADGE */
  'badge':'Now Accepting New Patients',
  /* SERVICES SECTION */
  'svc.lbl':'What We Offer','svc.ttl':'Services &amp; Insurance Coverage',
  'svc.desc':'Explore our full range of physician-supervised services and verify your insurance coverage below.',
  'tab.svc':'Services Offered','tab.ins':'Insurances Accepted',
  /* SERVICE TABLE */
  'th.svc':'Service','th.desc':'Description &amp; Highlights','th.price':'Pricing / Notes',
  'svc1.name':'Sleep Medicine',
  'svc1.desc':'Board-certified physicians diagnosing and treating the full spectrum of sleep disorders. State-of-the-art diagnostics with personalized treatment plans to restore healthy, restorative sleep.',
  'svc1.price':'Most major insurance plans accepted. Call to verify.',
  'svc2.name':'Weight Loss Program',
  'svc2.desc':'Our Tirzepatide program combines clinically proven GLP-1/GIP receptor agonist injections with physician oversight, nutritional guidance, and lifestyle coaching for sustainable, real results.',
  'svc2.price.note':'Price locked 6&nbsp;months if you book now for June!',
  'svc3.name':'IV Therapy',
  'svc3.desc':'Vitamins, minerals, and hydration delivered directly into the bloodstream for maximum absorption and fast results. Each infusion is customized by our clinical team to meet your specific needs.',
  'svc3.price':'Call for current pricing',
  'svc4.name':'Wellness &amp; More',
  'svc4.desc':'Whole-person care beyond our core services &mdash; a growing range of wellness treatments and consultations designed to support your long-term health journey.',
  'svc4.price':'Call for availability and pricing',
  /* INSURANCE */
  'ins.th':'Currently Accepted Insurance Carriers',
  'ins.note.h4':'Questions About Your Coverage?',
  'ins.note.p1':'We accept most major insurance plans. Coverage and benefits vary by plan. Our billing team is happy to verify your insurance benefits before your visit.',
  'ins.note.p2':'Contact us at <strong style="color:var(--dg)">727-472-9112</strong> and we will work with you to understand your coverage, co-pays, and out-of-pocket costs.',
  'ins.note.p3':'We believe finances should never be a barrier to good health.',
  /* ABOUT */
  'about.lbl':'Who We Are','about.ttl':'About West Coast Sleep Clinic',
  'about.p1':'At West Coast Sleep Clinic, we are committed to improving the lives of our patients through expert sleep medicine, innovative wellness programs, and compassionate, personalized care.',
  'about.p2':'Sleep is the foundation of good health. When you sleep better, you feel better, think more clearly, and live more fully. Our team of board-certified physicians and dedicated clinical staff work together to ensure every patient receives the individualized attention and care they deserve.',
  'about.p3':'Founded in 2023 and located in Largo, Florida, West Coast Sleep Clinic is proud to serve patients throughout Pinellas County and the surrounding Tampa Bay region.',
  'info.h4':'Practice Information',
  'info.loc.l':'Location','info.phone.l':'Phone / Text','info.hrs.l':'Hours','info.founded.l':'Founded','info.tele.l':'Telehealth',
  'info.hrs.v':'Mon &ndash; Fri: 8 AM &ndash; 5 PM','info.founded.v':'2023','info.tele.v':'Available',
  /* PROMISE */
  'promise.lbl':'Our Promise','promise.ttl':'Why Choose West Coast Sleep Clinic?',
  'p1.h4':'Expert Care','p1.p':'Board-certified physicians providing the highest standard of evidence-based clinical care for every patient, every visit.',
  'p2.h4':'Personalized Solutions','p2.p':'Every patient is unique. We design individualized treatment plans tailored to your specific needs, goals, and lifestyle.',
  'p3.h4':'Your Health, Our Priority','p3.p':'Your long-term health, comfort, and wellbeing are at the center of every decision we make. We are committed to real, lasting results.',
  /* FOOTER */
  'foot.copy':'&copy; 2023 West Coast Sleep Clinic &nbsp;&middot;&nbsp; Largo, Florida',
  /* REGISTRATION PAGE */
  'reg.h2':'Patient Registration','reg.sub':'Please complete all forms below. Use the Next button to proceed through each step.',
  'step.1':'Patient Reg','step.2':'Consent to Treat','step.3':'Financial Policy','step.4':'HIPAA Notice','step.5':'Text/Tele Consent','step.6':'Auth to Release','step.7':'Questionnaire',
  's1.ttl':'Patient Registration','s1.sub':'Please fill in your personal and insurance information completely.',
  's1.req':'<span>*</span> Indicates a required field',
  's1.sec.demo':'Patient Demographics',
  's1.fn':'First Name <span class="req">*</span>','s1.ln':'Last Name <span class="req">*</span>','s1.mi':'Middle Initial',
  's1.dob':'Date of Birth <span class="req">*</span>','s1.age':'Age','s1.sex':'Sex',
  's1.male':'Male','s1.female':'Female','s1.other':'Other',
  's1.ssn':'Social Security #','s1.dl':'Driver\'s License #','s1.addr':'Street Address',
  's1.city':'City','s1.state':'State','s1.zip':'Zip Code',
  's1.hphone':'Home Phone','s1.cphone':'Cell Phone',
  's1.email':'Email Address <span class="req">*</span>',
  's1.marital':'Marital Status','s1.single':'Single','s1.married':'Married','s1.divorced':'Divorced','s1.widowed':'Widowed',
  's1.employer':'Employer','s1.occ':'Occupation',
  's1.sec.ec':'Emergency Contact','s1.ec.name':'Contact Name','s1.ec.rel':'Relationship','s1.ec.phone':'Contact Phone',
  's1.sec.ins':'Insurance Information',
  's1.ins1':'Primary Insurance Company','s1.ph.name':'Policy Holder Name','s1.ph.rel':'Relationship to Patient',
  's1.member_id':'Member ID #','s1.group':'Group #',
  's1.ins2':'Secondary Insurance (if any)','s1.member_id2':'Secondary Member ID #',
  's1.pcp':'Primary Care Provider (PCP)','s1.ref':'Referring Provider',
  's1.sec.pharm':'Preferred Pharmacy','s1.pharm.name':'Pharmacy Name','s1.pharm.addr':'Pharmacy Address','s1.pharm.phone':'Pharmacy Phone',
  's1.next':'Next: Consent to Treat &rarr;',
  's2.ttl':'Consent to Treat','s2.sub':'Please read carefully and sign below.',
  's2.policy':'<h4>Consent to Treatment</h4><p>I hereby consent to and authorize West Coast Sleep Clinic and its physicians, nurses, and medical staff to provide medical evaluation, diagnosis, and treatment that they deem appropriate for my care. I understand that the practice of medicine is not an exact science, and that no guarantees or assurances have been made regarding the outcome of any treatment or procedure.</p><p>I consent to physical examinations, diagnostic tests (including blood draws, sleep studies, imaging, and other procedures), medical treatments, and the administration of medications as deemed necessary by the treating physician.</p><p>I understand that I may refuse any treatment or procedure at any time, and that I have the right to ask questions about any recommended treatment before consenting to it. I have the right to be informed about my diagnosis, the nature and purpose of any proposed treatment, the risks and benefits, and any alternative treatments available.</p><p>I acknowledge that I have received and reviewed the Notice of Privacy Practices describing how my protected health information may be used and disclosed. I authorize West Coast Sleep Clinic to use my health information as described in that notice.</p><p>I authorize West Coast Sleep Clinic to bill my insurance company or other third-party payer on my behalf for services rendered. I understand that I am ultimately responsible for any charges not covered by my insurance.</p>',
  's2.chk':'I have read and understand the Consent to Treatment above, and I consent to the treatment and authorization described.',
  's2.sig':'Patient (or Guardian) Signature <span class="req">*</span>','s2.date':'Date',
  's2.back':'&larr; Back','s2.next':'Next: Financial Policy &rarr;',
  's3.ttl':'Financial Policy','s3.sub':'Please read our financial policy and acknowledge below.',
  's3.policy':'<h4>Patient Financial Policy</h4><p><strong>Co-pays, Deductibles &amp; Co-insurance:</strong> All co-pays, deductibles, and co-insurance amounts are due at the time of service. We accept cash, check, and major credit/debit cards.</p><p><strong>Insurance Billing:</strong> We will bill your insurance company as a courtesy. You are responsible for ensuring that we have current and accurate insurance information. If your insurance does not pay within 60 days, the balance will become your responsibility.</p><p><strong>Non-Covered Services:</strong> Some services may not be covered by your insurance plan. You will be financially responsible for these services.</p><p><strong>Referrals &amp; Prior Authorizations:</strong> If your insurance requires a referral or prior authorization, it is your responsibility to obtain this before your visit. Failure to do so may result in non-payment by your insurance, and you will be responsible for the full balance.</p><p><strong>Self-Pay Patients:</strong> Payment is due in full at the time of service. Please contact our billing office to discuss payment arrangements if needed.</p><p><strong>Returned Checks:</strong> A fee of $35.00 will be charged for any returned checks.</p><p><strong>Cancellations:</strong> We require 24 hours notice for appointment cancellations. Repeated late cancellations or no-shows may result in a fee.</p>',
  's3.chk':'I have read and understand the Financial Policy above, and I agree to abide by its terms.',
  's3.sig':'Patient (or Guardian) Signature <span class="req">*</span>','s3.date':'Date',
  's3.back':'&larr; Back','s3.next':'Next: HIPAA Notice &rarr;',
  's4.ttl':'HIPAA Notice of Privacy Practices','s4.sub':'Your privacy is important to us. Please review our Notice of Privacy Practices.',
  's4.policy':'<h4>Notice of Privacy Practices — Acknowledgment</h4><p>This notice describes how medical information about you may be used and disclosed and how you can get access to this information. Please review it carefully.</p><p><strong>Our Commitment to Your Privacy:</strong> West Coast Sleep Clinic is dedicated to maintaining the privacy of your protected health information (PHI). We are required by law to maintain the privacy of your PHI and to provide you with this notice regarding our legal duties and privacy practices.</p><p><strong>How We May Use Your Information:</strong> We may use or disclose your PHI for treatment purposes (such as sharing information with other providers involved in your care), payment purposes (such as billing your insurance company), and healthcare operations (such as quality assessment and improvement activities).</p><p><strong>Your Rights:</strong> You have the right to:<ul><li>Request a restriction on uses and disclosures of your PHI</li><li>Request confidential communications</li><li>Inspect and copy your PHI</li><li>Request an amendment to your PHI</li><li>Receive an accounting of disclosures</li><li>Receive a copy of this notice</li></ul></p><p><strong>Complaints:</strong> If you believe your privacy rights have been violated, you may file a complaint with our Privacy Officer or with the U.S. Department of Health and Human Services. We will not retaliate against you for filing a complaint.</p>',
  's4.chk':'I acknowledge that I have received and reviewed the Notice of Privacy Practices for West Coast Sleep Clinic.',
  's4.rep':'If you are signing on behalf of the patient, please explain your relationship:',
  's4.sig':'Patient (or Representative) Signature <span class="req">*</span>','s4.date':'Date',
  's4.back':'&larr; Back','s4.next':'Next: Text &amp; Tele Consent &rarr;',
  's5.ttl':'Text &amp; Telehealth Consent','s5.sub':'Please read and agree to the following communication consents.',
  's5.txt.sec':'Text Message Consent',
  's5.txt.policy':'<h4>Consent to Receive Text Messages</h4><p>By signing below, you consent to receive text messages (SMS) from West Coast Sleep Clinic at the mobile phone number(s) you have provided. These messages may include appointment reminders, health information, billing notifications, and other practice communications.</p><p><strong>Message and data rates may apply.</strong> Message frequency varies. You may opt out at any time by replying STOP to any text message. Reply HELP for help. Carriers are not liable for delayed or undelivered messages.</p><p>Text messaging is not a secure form of communication. By consenting, you understand and accept the risk that text messages may be intercepted. Do not send sensitive medical information via text message.</p>',
  's5.txt.chk':'I consent to receive text messages from West Coast Sleep Clinic as described above.',
  's5.txt.phone':'Best Cell Phone for Texts',
  's5.tele.sec':'Telehealth Consent',
  's5.tele.policy':'<h4>Consent to Telehealth Services</h4><p>Telehealth involves the use of electronic communications to enable healthcare providers to provide clinical services to patients using interactive audio, video, or data communications. I understand that telehealth services involve the communication of my personal medical information, both orally and visually, to healthcare practitioners located in other areas.</p><p><strong>Risks &amp; Benefits:</strong> I understand there are potential risks with telehealth including interruptions, unauthorized access, and technical difficulties. I understand that my healthcare provider may determine that the transmitted information is of insufficient quality to make medical or health decisions, and that I may need an in-person visit.</p><p><strong>Confidentiality:</strong> I understand that the laws that protect the privacy and security of my health information apply to telehealth services. West Coast Sleep Clinic will take steps to ensure my information is secure.</p><p>I understand I may refuse telehealth services at any time without affecting my right to future care or treatment.</p>',
  's5.tele.chk':'I consent to telehealth services as described above and understand the risks and benefits associated with receiving care via telehealth.',
  's5.sig':'Patient (or Guardian) Signature <span class="req">*</span>','s5.date':'Date',
  's5.back':'&larr; Back','s5.next':'Next: Authorization to Release &rarr;',
  's6.ttl':'Authorization to Release Medical Information','s6.sub':'Complete this form to authorize release of your medical records.',
  's6.ibox':'This authorization allows West Coast Sleep Clinic to release your medical records. You may leave optional fields blank if not applicable. You have the right to revoke this authorization at any time by notifying us in writing.',
  's6.rel.sec':'Release To','s6.rel.to':'Name or Organization <span class="req">*</span>','s6.rel.phone':'Phone / Fax','s6.rel.addr':'Address',
  's6.info.sec':'Information to Release',
  's6.entire':'Entire Medical Record','s6.notes':'Office Visit Notes / Progress Notes','s6.labs':'Lab Results',
  's6.imaging':'Imaging / Radiology Reports','s6.sleep':'Sleep Study Reports',
  's6.rx':'Prescription / Medication History','s6.billing':'Billing Records','s6.other_chk':'Other:',
  's6.other_spec':'Other (specify)','s6.det.sec':'Details',
  's6.purpose':'Purpose of Release','s6.dates':'Date Range of Records',
  's6.exp':'Authorization Expiration Date','s6.no_exp':'No Expiration (one-year default)',
  's6.chk':'I authorize the release of the medical information described above. I understand I may revoke this authorization at any time in writing. I understand that a photocopy or electronic copy of this authorization is as valid as the original.',
  's6.sig':'Patient (or Guardian) Signature <span class="req">*</span>','s6.date':'Date',
  's6.back':'&larr; Back','s6.next':'Next: Questionnaire &rarr;',
  's7.ttl':'Patient Questionnaire','s7.sub':'This helps our physicians understand your health history and sleep concerns.',
  's7.cc.sec':'Chief Complaint &amp; Sleep History',
  's7.cc.label':'What is your main reason for visiting today?',
  's7.hrs.label':'How many hours of sleep do you get per night?',
  's7.dur.label':'How long have you had this concern?',
  's7.bed.label':'Usual bedtime','s7.wake.label':'Usual wake time',
  's7.sym.label':'Sleep Symptoms (check all that apply)',
  's7.sym1':'Difficulty falling asleep','s7.sym2':'Waking up frequently during the night',
  's7.sym3':'Waking up too early and unable to return to sleep','s7.sym4':'Snoring',
  's7.sym5':'Witnessed pauses in breathing or gasping','s7.sym6':'Not feeling refreshed after sleep',
  's7.sym7':'Excessive daytime sleepiness','s7.sym8':'Restless legs or uncomfortable leg sensations at night',
  's7.sym9':'Teeth grinding or jaw clenching during sleep','s7.sym10':'Sleepwalking or talking in sleep',
  's7.prev.label':'Have you had a sleep study before?','s7.cpap.label':'Do you currently use CPAP or BiPAP?',
  's7.ess.sec':'Epworth Sleepiness Scale',
  's7.ess.intro':'How likely are you to doze off or fall asleep in the following situations? Rate each from 0–3:<br><strong>0</strong> = Would never doze &nbsp; <strong>1</strong> = Slight chance &nbsp; <strong>2</strong> = Moderate chance &nbsp; <strong>3</strong> = High chance',
  's7.ess.sit':'Situation',
  's7.ess1':'Sitting and reading','s7.ess2':'Watching TV','s7.ess3':'Sitting inactive in a public place',
  's7.ess4':'As a passenger in a car for an hour','s7.ess5':'Lying down in the afternoon when possible',
  's7.ess6':'Sitting and talking to someone','s7.ess7':'Sitting quietly after lunch (no alcohol)',
  's7.ess8':'In a car stopped for a few minutes in traffic',
  's7.hx.sec':'Medical History','s7.hx.intro':'Check all conditions that apply to you:',
  's7.hx1':'High Blood Pressure (Hypertension)','s7.hx2':'Diabetes (Type 1 or Type 2)',
  's7.hx3':'Heart Disease / Cardiac Condition','s7.hx4':'Atrial Fibrillation (AFib)','s7.hx5':'Stroke or TIA',
  's7.hx6':'Asthma','s7.hx7':'COPD / Emphysema','s7.hx8':'Anxiety / Panic Disorder','s7.hx9':'Depression',
  's7.hx10':'Thyroid Disorder','s7.hx11':'Obesity','s7.hx12':'GERD / Acid Reflux',
  's7.hx13':'Cancer (current or past)','s7.hx14':'Kidney Disease','s7.hx15':'Liver Disease',
  's7.hx.other':'Other Medical Conditions',
  's7.med.sec':'Medications &amp; Allergies',
  's7.med.label':'Current Medications (include dosages if known)','s7.allergy.label':'Known Drug Allergies',
  's7.add.sec':'Additional Information','s7.height':'Height','s7.weight':'Weight',
  's7.comments':'Additional Comments or Concerns',
  's7.back':'&larr; Back','s7.submit':'Submit Registration &#10003;',
  'done.h2':'Registration Complete!',
  'done.p1':'Thank you for completing your patient registration. Our team at West Coast Sleep Clinic has received your forms.',
  'done.p2':'We will contact you shortly to confirm your appointment. If you have any questions, please call or text us at <strong>727-472-9112</strong>.',
  'done.p3':'<em>Sleep Better. Feel Better. Live Better.</em>',
  'done.home':'Return to Home'
},
es: {
  /* NAV */
  'nav.home':'Inicio','nav.reg':'Registro de Paciente',
  /* BADGE */
  'badge':'Aceptando Nuevos Pacientes',
  /* SERVICES SECTION */
  'svc.lbl':'Lo Que Ofrecemos','svc.ttl':'Servicios &amp; Cobertura de Seguro',
  'svc.desc':'Explore nuestra gama completa de servicios supervisados por médicos y verifique su cobertura de seguro a continuación.',
  'tab.svc':'Servicios Ofrecidos','tab.ins':'Seguros Aceptados',
  /* SERVICE TABLE */
  'th.svc':'Servicio','th.desc':'Descripción &amp; Aspectos Destacados','th.price':'Precio / Notas',
  'svc1.name':'Medicina del Sueño',
  'svc1.desc':'Médicos certificados que diagnostican y tratan el espectro completo de trastornos del sueño. Diagnósticos de última generación con planes de tratamiento personalizados para restaurar un sueño saludable y reparador.',
  'svc1.price':'Se aceptan la mayoría de los planes de seguro. Llame para verificar.',
  'svc2.name':'Programa de Pérdida de Peso',
  'svc2.desc':'Nuestro programa de Tirzepatida combina inyecciones de agonistas de receptores GLP-1/GIP clínicamente probadas con supervisión médica, orientación nutricional y entrenamiento de estilo de vida para resultados sostenibles y reales.',
  'svc2.price.note':'¡Precio fijo por 6&nbsp;meses si reserva ahora para junio!',
  'svc3.name':'Terapia IV',
  'svc3.desc':'Vitaminas, minerales e hidratación administrados directamente en el torrente sanguíneo para una absorción máxima y resultados rápidos. Cada infusión es personalizada por nuestro equipo clínico para satisfacer sus necesidades específicas.',
  'svc3.price':'Llame para conocer los precios actuales',
  'svc4.name':'Bienestar &amp; Más',
  'svc4.desc':'Atención integral de la persona más allá de nuestros servicios principales &mdash; una gama creciente de tratamientos y consultas de bienestar diseñados para apoyar su viaje de salud a largo plazo.',
  'svc4.price':'Llame para disponibilidad y precios',
  /* INSURANCE */
  'ins.th':'Portadores de Seguro Actualmente Aceptados',
  'ins.note.h4':'¿Preguntas Sobre Su Cobertura?',
  'ins.note.p1':'Aceptamos la mayoría de los planes de seguro principales. La cobertura y los beneficios varían según el plan. Nuestro equipo de facturación con gusto verificará sus beneficios de seguro antes de su visita.',
  'ins.note.p2':'Contáctenos al <strong style="color:var(--dg)">727-472-9112</strong> y trabajaremos con usted para comprender su cobertura, copagos y costos de bolsillo.',
  'ins.note.p3':'Creemos que las finanzas nunca deben ser una barrera para una buena salud.',
  /* ABOUT */
  'about.lbl':'Quiénes Somos','about.ttl':'Acerca de West Coast Sleep Clinic',
  'about.p1':'En West Coast Sleep Clinic, estamos comprometidos a mejorar las vidas de nuestros pacientes a través de la medicina del sueño experta, programas de bienestar innovadores y atención compasiva y personalizada.',
  'about.p2':'El sueño es la base de una buena salud. Cuando duerme mejor, se siente mejor, piensa con más claridad y vive más plenamente. Nuestro equipo de médicos certificados y personal clínico dedicado trabaja junto para garantizar que cada paciente reciba la atención individualizada que merece.',
  'about.p3':'Fundado en 2023 y ubicado en Largo, Florida, West Coast Sleep Clinic se enorgullece de atender a pacientes en todo el condado de Pinellas y la región circundante de Tampa Bay.',
  'info.h4':'Información de la Práctica',
  'info.loc.l':'Ubicación','info.phone.l':'Teléfono / Texto','info.hrs.l':'Horario','info.founded.l':'Fundado','info.tele.l':'Telesalud',
  'info.hrs.v':'Lun &ndash; Vie: 8 AM &ndash; 5 PM','info.founded.v':'2023','info.tele.v':'Disponible',
  /* PROMISE */
  'promise.lbl':'Nuestra Promesa','promise.ttl':'¿Por Qué Elegir West Coast Sleep Clinic?',
  'p1.h4':'Cuidado Experto','p1.p':'Médicos certificados que brindan el más alto estándar de atención clínica basada en evidencia para cada paciente, en cada visita.',
  'p2.h4':'Soluciones Personalizadas','p2.p':'Cada paciente es único. Diseñamos planes de tratamiento individualizados adaptados a sus necesidades, objetivos y estilo de vida específicos.',
  'p3.h4':'Su Salud, Nuestra Prioridad','p3.p':'Su salud a largo plazo, comodidad y bienestar están en el centro de cada decisión que tomamos. Estamos comprometidos con resultados reales y duraderos.',
  /* FOOTER */
  'foot.copy':'&copy; 2023 West Coast Sleep Clinic &nbsp;&middot;&nbsp; Largo, Florida',
  /* REGISTRATION PAGE */
  'reg.h2':'Registro de Paciente','reg.sub':'Por favor complete todos los formularios. Use el botón Siguiente para proceder en cada paso.',
  'step.1':'Reg. Paciente','step.2':'Consentimiento','step.3':'Pol. Financiera','step.4':'Aviso HIPAA','step.5':'Texto/Tele','step.6':'Autorización','step.7':'Cuestionario',
  's1.ttl':'Registro de Paciente','s1.sub':'Por favor complete su información personal y de seguro completamente.',
  's1.req':'<span>*</span> Indica un campo requerido',
  's1.sec.demo':'Datos Demográficos del Paciente',
  's1.fn':'Nombre <span class="req">*</span>','s1.ln':'Apellido <span class="req">*</span>','s1.mi':'Inicial del Segundo Nombre',
  's1.dob':'Fecha de Nacimiento <span class="req">*</span>','s1.age':'Edad','s1.sex':'Sexo',
  's1.male':'Masculino','s1.female':'Femenino','s1.other':'Otro',
  's1.ssn':'# de Seguro Social','s1.dl':'# de Licencia de Conducir','s1.addr':'Dirección',
  's1.city':'Ciudad','s1.state':'Estado','s1.zip':'Código Postal',
  's1.hphone':'Teléfono del Hogar','s1.cphone':'Teléfono Celular',
  's1.email':'Correo Electrónico <span class="req">*</span>',
  's1.marital':'Estado Civil','s1.single':'Soltero/a','s1.married':'Casado/a','s1.divorced':'Divorciado/a','s1.widowed':'Viudo/a',
  's1.employer':'Empleador','s1.occ':'Ocupación',
  's1.sec.ec':'Contacto de Emergencia','s1.ec.name':'Nombre del Contacto','s1.ec.rel':'Relación','s1.ec.phone':'Teléfono del Contacto',
  's1.sec.ins':'Información de Seguro',
  's1.ins1':'Compañía de Seguro Principal','s1.ph.name':'Nombre del Titular de la Póliza','s1.ph.rel':'Relación con el Paciente',
  's1.member_id':'# de Miembro','s1.group':'# de Grupo',
  's1.ins2':'Seguro Secundario (si aplica)','s1.member_id2':'# de Miembro Secundario',
  's1.pcp':'Médico de Atención Primaria (MAP)','s1.ref':'Médico que Refiere',
  's1.sec.pharm':'Farmacia de Preferencia','s1.pharm.name':'Nombre de la Farmacia','s1.pharm.addr':'Dirección de la Farmacia','s1.pharm.phone':'Teléfono de la Farmacia',
  's1.next':'Siguiente: Consentimiento &rarr;',
  's2.ttl':'Consentimiento para Tratamiento','s2.sub':'Por favor lea con atención y firme a continuación.',
  's2.policy':'<h4>Consentimiento para Tratamiento</h4><p>Por medio de la presente, doy mi consentimiento y autorizo a West Coast Sleep Clinic y a sus médicos, enfermeras y personal médico a proporcionar evaluación médica, diagnóstico y tratamiento que consideren apropiados para mi atención. Entiendo que la práctica de la medicina no es una ciencia exacta, y que no se han hecho garantías sobre el resultado de ningún tratamiento.</p><p>Doy mi consentimiento para exámenes físicos, pruebas de diagnóstico (incluyendo extracción de sangre, estudios del sueño, imágenes y otros procedimientos), tratamientos médicos y administración de medicamentos según lo considere necesario el médico tratante.</p><p>Entiendo que puedo rechazar cualquier tratamiento en cualquier momento, y que tengo el derecho de hacer preguntas sobre cualquier tratamiento recomendado antes de dar mi consentimiento. Tengo el derecho de ser informado sobre mi diagnóstico, los riesgos y beneficios, y los tratamientos alternativos disponibles.</p><p>Reconozco que he recibido y revisado el Aviso de Prácticas de Privacidad. Autorizo a West Coast Sleep Clinic a usar mi información de salud como se describe en ese aviso.</p><p>Autorizo a West Coast Sleep Clinic a facturar a mi compañía de seguros en mi nombre. Entiendo que soy responsable de los cargos no cubiertos por mi seguro.</p>',
  's2.chk':'He leído y entiendo el Consentimiento para Tratamiento, y doy mi consentimiento para el tratamiento y la autorización descritos.',
  's2.sig':'Firma del Paciente (o Tutor) <span class="req">*</span>','s2.date':'Fecha',
  's2.back':'&larr; Atrás','s2.next':'Siguiente: Política Financiera &rarr;',
  's3.ttl':'Política Financiera','s3.sub':'Por favor lea nuestra política financiera y confirme a continuación.',
  's3.policy':'<h4>Política Financiera del Paciente</h4><p><strong>Copagos, Deducibles y Co-seguros:</strong> Todos los copagos, deducibles y montos de co-seguro se deben pagar al momento del servicio. Aceptamos efectivo, cheque y tarjetas de crédito/débito principales.</p><p><strong>Facturación de Seguros:</strong> Facturaremos a su compañía de seguros por cortesía. Usted es responsable de garantizar que tengamos información de seguro actual y precisa. Si su seguro no paga dentro de 60 días, el saldo será su responsabilidad.</p><p><strong>Servicios No Cubiertos:</strong> Algunos servicios pueden no estar cubiertos por su plan de seguro. Usted será financieramente responsable de estos servicios.</p><p><strong>Referencias y Autorizaciones Previas:</strong> Si su seguro requiere una referencia o autorización previa, es su responsabilidad obtenerla antes de su visita.</p><p><strong>Pacientes de Pago Directo:</strong> El pago se debe en su totalidad al momento del servicio.</p><p><strong>Cheques Devueltos:</strong> Se cobrará una tarifa de $35.00 por cualquier cheque devuelto.</p><p><strong>Cancelaciones:</strong> Requerimos 24 horas de aviso para cancelaciones de citas. Las cancelaciones tardías repetidas pueden resultar en un cargo.</p>',
  's3.chk':'He leído y entiendo la Política Financiera, y acepto cumplir con sus términos.',
  's3.sig':'Firma del Paciente (o Tutor) <span class="req">*</span>','s3.date':'Fecha',
  's3.back':'&larr; Atrás','s3.next':'Siguiente: Aviso HIPAA &rarr;',
  's4.ttl':'Aviso HIPAA de Prácticas de Privacidad','s4.sub':'Su privacidad es importante para nosotros. Por favor revise nuestro Aviso de Prácticas de Privacidad.',
  's4.policy':'<h4>Aviso de Prácticas de Privacidad — Reconocimiento</h4><p>Este aviso describe cómo se puede usar y divulgar su información médica y cómo puede acceder a ella. Por favor revíselo detenidamente.</p><p><strong>Nuestro Compromiso con su Privacidad:</strong> West Coast Sleep Clinic está dedicado a mantener la privacidad de su información de salud protegida (PHI). Estamos obligados por ley a mantener la privacidad de su PHI.</p><p><strong>Cómo Podemos Usar su Información:</strong> Podemos usar o divulgar su PHI para propósitos de tratamiento, pago y operaciones de atención médica.</p><p><strong>Sus Derechos:</strong> Usted tiene el derecho de:<ul><li>Solicitar una restricción sobre usos y divulgaciones de su PHI</li><li>Solicitar comunicaciones confidenciales</li><li>Inspeccionar y copiar su PHI</li><li>Solicitar una enmienda a su PHI</li><li>Recibir un registro de divulgaciones</li><li>Recibir una copia de este aviso</li></ul></p><p><strong>Quejas:</strong> Si cree que sus derechos de privacidad han sido violados, puede presentar una queja con nuestro Oficial de Privacidad o con el Departamento de Salud y Servicios Humanos de los EE. UU.</p>',
  's4.chk':'Reconozco que he recibido y revisado el Aviso de Prácticas de Privacidad de West Coast Sleep Clinic.',
  's4.rep':'Si está firmando en nombre del paciente, por favor explique su relación:',
  's4.sig':'Firma del Paciente (o Representante) <span class="req">*</span>','s4.date':'Fecha',
  's4.back':'&larr; Atrás','s4.next':'Siguiente: Consentimiento Texto/Tele &rarr;',
  's5.ttl':'Consentimiento de Texto y Telesalud','s5.sub':'Por favor lea y acepte los siguientes consentimientos de comunicación.',
  's5.txt.sec':'Consentimiento para Mensajes de Texto',
  's5.txt.policy':'<h4>Consentimiento para Recibir Mensajes de Texto</h4><p>Al firmar a continuación, usted consiente recibir mensajes de texto (SMS) de West Coast Sleep Clinic en el número de teléfono móvil que ha proporcionado. Estos mensajes pueden incluir recordatorios de citas, información de salud y otras comunicaciones de la práctica.</p><p><strong>Se pueden aplicar tarifas de mensajes y datos.</strong> La frecuencia de mensajes varía. Puede cancelar la suscripción en cualquier momento respondiendo STOP a cualquier mensaje de texto.</p><p>Los mensajes de texto no son una forma segura de comunicación. Al dar su consentimiento, entiende y acepta el riesgo de que los mensajes de texto puedan ser interceptados. No envíe información médica confidencial por mensaje de texto.</p>',
  's5.txt.chk':'Doy mi consentimiento para recibir mensajes de texto de West Coast Sleep Clinic como se describe.',
  's5.txt.phone':'Mejor Teléfono Celular para Textos',
  's5.tele.sec':'Consentimiento de Telesalud',
  's5.tele.policy':'<h4>Consentimiento para Servicios de Telesalud</h4><p>La telesalud implica el uso de comunicaciones electrónicas para permitir que los proveedores de atención médica brinden servicios clínicos a los pacientes. Entiendo que los servicios de telesalud implican la comunicación de mi información médica personal, tanto oralmente como visualmente, a profesionales de la salud ubicados en otras áreas.</p><p><strong>Riesgos y Beneficios:</strong> Entiendo que existen riesgos potenciales con la telesalud, incluyendo interrupciones, acceso no autorizado y dificultades técnicas. Entiendo que mi proveedor de atención médica puede determinar que necesita una visita en persona.</p><p><strong>Confidencialidad:</strong> Entiendo que las leyes que protegen la privacidad y seguridad de mi información de salud se aplican a los servicios de telesalud. West Coast Sleep Clinic tomará medidas para garantizar que mi información sea segura.</p><p>Entiendo que puedo rechazar los servicios de telesalud en cualquier momento sin afectar mi derecho a atención futura.</p>',
  's5.tele.chk':'Doy mi consentimiento para los servicios de telesalud y entiendo los riesgos y beneficios asociados.',
  's5.sig':'Firma del Paciente (o Tutor) <span class="req">*</span>','s5.date':'Fecha',
  's5.back':'&larr; Atrás','s5.next':'Siguiente: Autorización para Divulgar &rarr;',
  's6.ttl':'Autorización para Divulgar Información Médica','s6.sub':'Complete este formulario para autorizar la divulgación de sus registros médicos.',
  's6.ibox':'Esta autorización permite a West Coast Sleep Clinic divulgar sus registros médicos. Puede dejar los campos opcionales en blanco. Tiene el derecho de revocar esta autorización en cualquier momento por escrito.',
  's6.rel.sec':'Divulgar A','s6.rel.to':'Nombre u Organización <span class="req">*</span>','s6.rel.phone':'Teléfono / Fax','s6.rel.addr':'Dirección',
  's6.info.sec':'Información a Divulgar',
  's6.entire':'Registro Médico Completo','s6.notes':'Notas de Visitas / Notas de Progreso','s6.labs':'Resultados de Laboratorio',
  's6.imaging':'Informes de Imágenes / Radiología','s6.sleep':'Informes de Estudio del Sueño',
  's6.rx':'Historial de Recetas / Medicamentos','s6.billing':'Registros de Facturación','s6.other_chk':'Otro:',
  's6.other_spec':'Otro (especificar)','s6.det.sec':'Detalles',
  's6.purpose':'Propósito de la Divulgación','s6.dates':'Rango de Fechas de los Registros',
  's6.exp':'Fecha de Vencimiento de la Autorización','s6.no_exp':'Sin Vencimiento (predeterminado un año)',
  's6.chk':'Autorizo la divulgación de la información médica descrita. Entiendo que puedo revocar esta autorización en cualquier momento por escrito.',
  's6.sig':'Firma del Paciente (o Tutor) <span class="req">*</span>','s6.date':'Fecha',
  's6.back':'&larr; Atrás','s6.next':'Siguiente: Cuestionario &rarr;',
  's7.ttl':'Cuestionario del Paciente','s7.sub':'Esto ayuda a nuestros médicos a entender su historial de salud y preocupaciones sobre el sueño.',
  's7.cc.sec':'Queja Principal e Historial del Sueño',
  's7.cc.label':'¿Cuál es su razón principal para visitar hoy?',
  's7.hrs.label':'¿Cuántas horas de sueño obtiene por noche?',
  's7.dur.label':'¿Hace cuánto tiempo tiene esta preocupación?',
  's7.bed.label':'Hora habitual de acostarse','s7.wake.label':'Hora habitual de levantarse',
  's7.sym.label':'Síntomas de Sueño (marque todos los que apliquen)',
  's7.sym1':'Dificultad para conciliar el sueño','s7.sym2':'Despertar frecuentemente durante la noche',
  's7.sym3':'Despertar demasiado temprano y no poder volver a dormir','s7.sym4':'Ronquidos',
  's7.sym5':'Pausas presenciadas en la respiración o jadeos','s7.sym6':'No sentirse descansado después de dormir',
  's7.sym7':'Somnolencia excesiva durante el día','s7.sym8':'Piernas inquietas o sensaciones incómodas en las piernas durante la noche',
  's7.sym9':'Rechinar o apretar los dientes durante el sueño','s7.sym10':'Sonambulismo o hablar durante el sueño',
  's7.prev.label':'¿Ha tenido un estudio del sueño antes?','s7.cpap.label':'¿Usa actualmente CPAP o BiPAP?',
  's7.ess.sec':'Escala de Somnolencia de Epworth',
  's7.ess.intro':'¿Qué probabilidad hay de que se quede dormido en las siguientes situaciones? Evalúe del 0 al 3:<br><strong>0</strong> = Nunca se quedaría dormido &nbsp; <strong>1</strong> = Poca probabilidad &nbsp; <strong>2</strong> = Moderada probabilidad &nbsp; <strong>3</strong> = Alta probabilidad',
  's7.ess.sit':'Situación',
  's7.ess1':'Sentado leyendo','s7.ess2':'Viendo televisión','s7.ess3':'Sentado inactivo en un lugar público',
  's7.ess4':'Como pasajero en un automóvil por una hora','s7.ess5':'Acostado en la tarde cuando es posible',
  's7.ess6':'Sentado conversando con alguien','s7.ess7':'Sentado tranquilamente después del almuerzo (sin alcohol)',
  's7.ess8':'En un automóvil detenido unos minutos en el tráfico',
  's7.hx.sec':'Historial Médico','s7.hx.intro':'Marque todas las condiciones que le apliquen:',
  's7.hx1':'Presión Arterial Alta (Hipertensión)','s7.hx2':'Diabetes (Tipo 1 o Tipo 2)',
  's7.hx3':'Enfermedad Cardíaca / Condición Cardíaca','s7.hx4':'Fibrilación Auricular (FA)','s7.hx5':'Derrame Cerebral o AIT',
  's7.hx6':'Asma','s7.hx7':'EPOC / Enfisema','s7.hx8':'Ansiedad / Trastorno de Pánico','s7.hx9':'Depresión',
  's7.hx10':'Trastorno Tiroideo','s7.hx11':'Obesidad','s7.hx12':'ERGE / Reflujo Ácido',
  's7.hx13':'Cáncer (actual o pasado)','s7.hx14':'Enfermedad Renal','s7.hx15':'Enfermedad Hepática',
  's7.hx.other':'Otras Condiciones Médicas',
  's7.med.sec':'Medicamentos y Alergias',
  's7.med.label':'Medicamentos Actuales (incluir dosis si se conocen)','s7.allergy.label':'Alergias a Medicamentos Conocidas',
  's7.add.sec':'Información Adicional','s7.height':'Estatura','s7.weight':'Peso',
  's7.comments':'Comentarios o Preocupaciones Adicionales',
  's7.back':'&larr; Atrás','s7.submit':'Enviar Registro &#10003;',
  'done.h2':'¡Registro Completado!',
  'done.p1':'Gracias por completar su registro de paciente. Nuestro equipo en West Coast Sleep Clinic ha recibido sus formularios.',
  'done.p2':'Nos comunicaremos con usted pronto para confirmar su cita. Si tiene preguntas, llame o envíe un mensaje al <strong>727-472-9112</strong>.',
  'done.p3':'<em>Duerma Mejor. Siéntase Mejor. Viva Mejor.</em>',
  'done.home':'Volver al Inicio'
}
};

function setLang(lang) {
  currentLang = lang;
  document.documentElement.lang = lang;
  ['btnEN','btnEN2'].forEach(function(id){ var b=document.getElementById(id); if(b) b.classList.toggle('active', lang==='en'); });
  ['btnES','btnES2'].forEach(function(id){ var b=document.getElementById(id); if(b) b.classList.toggle('active', lang==='es'); });
  var tmap = T[lang] || T['en'];
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (tmap[key] !== undefined) el.innerHTML = tmap[key];
  });
  var heroLogo = document.querySelector('.hero-logo');
  if (heroLogo) heroLogo.src = lang === 'es' ? 'wcsc-logo-spanish.png' : 'westcoast sleep clinic logo - Editedv2.png';
  try { localStorage.setItem('wcsc_lang', lang); } catch(e) {}
}

document.addEventListener('DOMContentLoaded', function() {
  var saved = 'en';
  try { saved = localStorage.getItem('wcsc_lang') || 'en'; } catch(e) {}
  setLang(saved);
});
